name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcairo2-dev \
          libgirepository1.0-dev \
          gir1.2-glib-2.0 \
          python3-gi \
          python3-gi-cairo \
          gobject-introspection \
          libglib2.0-dev \
          pkg-config
        dpkg -l | grep girepository || echo "girepository not found!"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run README updater
        run: python3 main.py 

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🤖 Auto-update README" || echo "No changes to commit"
          git push
